source("compute-results.R")

.indisting <- sprintf("%0.0f\\%%", 100 * (36 - cmp_ndiff) / 36)

.lower_benefit <- sprintf("%0.0f\\%%", min(dat_casesum[["min"]]))

.upper_benefit <- sprintf("%0.0f\\%%", max(dat_casesum[["max"]]))

txt <- "Measurements taken during experiments are perturbed by time-dependent nuisance variation, due to factors such as learning or fatigue. Researchers can improve power by controlling for these effects using either a model-based approach (e.g., a Generalized Additive Mixed Models with Wiggly Intercepts, or WIMs), or a design-based approach (e.g., Permuted Subblock Randomization, or PSR). We used Monte Carlo simulations to compare the power advantage of using WIMs versus PSR across 36 scenarios combining nine different study designs and four types of temporally structured error (learning effect, random walk, pink noise, and mixed). In nearly all scenarios, WIMs and PSR reliably improved power as compared to an uncorrected baseline, within a range of {.lower_benefit} to {.upper_benefit}. Power was especially enhanced for studies with smaller numbers of trials. In {.indisting} of cases, both approaches yielded similar boosts in power. For data with a learning effect, a random walk, or a mixed structure, WIMs often outperformed PSR, usually by a large margin; for pink noise, PSR modestly outperformed WIMs. There was no consistent added benefit of combining the two approaches. We close with practical recommendations for researchers."

outfile <- "abstract.tex"
         
cat("%% do not edit this file directly... it is generated by make-abstract.R",
    glue::glue(txt),
    file=outfile, sep = "\n")

message("wrote abstract to '", outfile, "'")

