// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// test_pink
std::vector<double> test_pink(const int& n, const double& d);
RcppExport SEXP _psrsim_test_pink(SEXP nSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type n(nSEXP);
    Rcpp::traits::input_parameter< const double& >::type d(dSEXP);
    rcpp_result_gen = Rcpp::wrap(test_pink(n, d));
    return rcpp_result_gen;
END_RCPP
}
// test_psr
std::vector<int> test_psr(const int& n_obs, const int& n_subblocks);
RcppExport SEXP _psrsim_test_psr(SEXP n_obsSEXP, SEXP n_subblocksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const int& >::type n_obs(n_obsSEXP);
    Rcpp::traits::input_parameter< const int& >::type n_subblocks(n_subblocksSEXP);
    rcpp_result_gen = Rcpp::wrap(test_psr(n_obs, n_subblocks));
    return rcpp_result_gen;
END_RCPP
}
// simdata_1f_int
DataFrame simdata_1f_int(int nPart, int nLevels, int nReps, int nSubblocks, double mu, double eta, double prop_rint, double prop_rslp, int estr_id);
RcppExport SEXP _psrsim_simdata_1f_int(SEXP nPartSEXP, SEXP nLevelsSEXP, SEXP nRepsSEXP, SEXP nSubblocksSEXP, SEXP muSEXP, SEXP etaSEXP, SEXP prop_rintSEXP, SEXP prop_rslpSEXP, SEXP estr_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nPart(nPartSEXP);
    Rcpp::traits::input_parameter< int >::type nLevels(nLevelsSEXP);
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    Rcpp::traits::input_parameter< int >::type nSubblocks(nSubblocksSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type prop_rint(prop_rintSEXP);
    Rcpp::traits::input_parameter< double >::type prop_rslp(prop_rslpSEXP);
    Rcpp::traits::input_parameter< int >::type estr_id(estr_idSEXP);
    rcpp_result_gen = Rcpp::wrap(simdata_1f_int(nPart, nLevels, nReps, nSubblocks, mu, eta, prop_rint, prop_rslp, estr_id));
    return rcpp_result_gen;
END_RCPP
}
// simdata_2x2ww_int
DataFrame simdata_2x2ww_int(int nPart, int nReps, int nSubblocks, double mu, double eta_row, double eta_col, double eta_rcx, double prop_rint, double prop_rslp_row, double prop_rslp_col, double prop_rslp_rcx, int estr_id);
RcppExport SEXP _psrsim_simdata_2x2ww_int(SEXP nPartSEXP, SEXP nRepsSEXP, SEXP nSubblocksSEXP, SEXP muSEXP, SEXP eta_rowSEXP, SEXP eta_colSEXP, SEXP eta_rcxSEXP, SEXP prop_rintSEXP, SEXP prop_rslp_rowSEXP, SEXP prop_rslp_colSEXP, SEXP prop_rslp_rcxSEXP, SEXP estr_idSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type nPart(nPartSEXP);
    Rcpp::traits::input_parameter< int >::type nReps(nRepsSEXP);
    Rcpp::traits::input_parameter< int >::type nSubblocks(nSubblocksSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type eta_row(eta_rowSEXP);
    Rcpp::traits::input_parameter< double >::type eta_col(eta_colSEXP);
    Rcpp::traits::input_parameter< double >::type eta_rcx(eta_rcxSEXP);
    Rcpp::traits::input_parameter< double >::type prop_rint(prop_rintSEXP);
    Rcpp::traits::input_parameter< double >::type prop_rslp_row(prop_rslp_rowSEXP);
    Rcpp::traits::input_parameter< double >::type prop_rslp_col(prop_rslp_colSEXP);
    Rcpp::traits::input_parameter< double >::type prop_rslp_rcx(prop_rslp_rcxSEXP);
    Rcpp::traits::input_parameter< int >::type estr_id(estr_idSEXP);
    rcpp_result_gen = Rcpp::wrap(simdata_2x2ww_int(nPart, nReps, nSubblocks, mu, eta_row, eta_col, eta_rcx, prop_rint, prop_rslp_row, prop_rslp_col, prop_rslp_rcx, estr_id));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_psrsim_test_pink", (DL_FUNC) &_psrsim_test_pink, 2},
    {"_psrsim_test_psr", (DL_FUNC) &_psrsim_test_psr, 2},
    {"_psrsim_simdata_1f_int", (DL_FUNC) &_psrsim_simdata_1f_int, 9},
    {"_psrsim_simdata_2x2ww_int", (DL_FUNC) &_psrsim_simdata_2x2ww_int, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_psrsim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
