# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_pink <- function(n, d) {
    .Call(`_psrsim_test_pink`, n, d)
}

test_psr <- function(n_obs, n_subblocks) {
    .Call(`_psrsim_test_psr`, n_obs, n_subblocks)
}

simdata_1f_int <- function(nPart, nLevels, nReps, nSubblocks, mu, eta, prop_rint, prop_rslp, estr_id) {
    .Call(`_psrsim_simdata_1f_int`, nPart, nLevels, nReps, nSubblocks, mu, eta, prop_rint, prop_rslp, estr_id)
}

simdata_2x2ww_int <- function(nPart, nReps, nSubblocks, mu, eta_row, eta_col, eta_rcx, prop_rint, prop_rslp_row, prop_rslp_col, prop_rslp_rcx, estr_id) {
    .Call(`_psrsim_simdata_2x2ww_int`, nPart, nReps, nSubblocks, mu, eta_row, eta_col, eta_rcx, prop_rint, prop_rslp_row, prop_rslp_col, prop_rslp_rcx, estr_id)
}

